server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        - id: hr-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/hr/**,/api/settings/**
          filters:
            - StripPrefix=0
            - name: JwtAuthFilter

        - id: attendance-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/attendance/**
          filters:
            - StripPrefix=0
            - name: JwtAuthFilter

        - id: payroll-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/payroll/**
          filters:
            - StripPrefix=0
            - name: JwtAuthFilter

        - id: report-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=0
            - name: JwtAuthFilter

app:
  jwt:
    secret: "TGFybV9TZWN1cmUhQDIwMjZfR2FybWVudEhSU3lzdGVtX1NlY3JldEtleV8xMjM="
    expiration: 28800000  # 8 hours in ms

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
