server:
  port: 8082

spring:
  application:
    name: hr-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dbTheGarment
    username: postgres
    password: Vp123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: false   # Schema managed externally

app:
  jwt:
    secret: "TGFybV9TZWN1cmUhQDIwMjZfR2FybWVudEhSU3lzdGVtX1NlY3JldEtleV8xMjM="

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
