server:
  port: 8080

spring:
  application:
    name: tg-bff-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true
    filter: true
    url: /v3/api-docs?group=bff
